# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "autonomous-engineer-discord-bot"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
